"""Tests for TUI components (SettingsScreen, ExportScreen, OutputPanel, DebugPanel).

Documentation generated by LLM - requires human review
pre-1.0.0 - APIs and contracts may change
"""

from contextlib import asynccontextmanager
from typing import Any
from unittest.mock import MagicMock, patch

import pytest

try:
    from textual.app import App, ComposeResult
    from textual.widgets import Static

    from wxpath.tui import DebugPanel, ExportScreen, OutputPanel, SettingsScreen
except ImportError:
    pytest.skip("textual not available", allow_module_level=True)


@asynccontextmanager
async def run_widget_app(widget: Any) -> tuple[Any, Any]:
    """Run a single widget inside a minimal Textual App for testing."""

    class _WidgetApp(App):
        def compose(self) -> ComposeResult:  # type: ignore[override]
            yield widget

    app = _WidgetApp()
    async with app.run_test() as pilot:  # type: ignore[attr-defined]
        yield widget, pilot


class TestOutputPanel:
    """Test the OutputPanel component."""

    def test_output_panel_initialization(self):
        """Test OutputPanel initializes correctly."""
        panel = OutputPanel()
        assert panel.border_title == "Output"

    @pytest.mark.asyncio
    async def test_output_panel_clear(self):
        """Test clearing the output panel."""
        panel = OutputPanel()
        async with run_widget_app(panel) as (mounted_panel, pilot):
            mounted_panel.mount(Static("Test content"))
            await pilot.pause()
            assert len(mounted_panel.children) > 0
            mounted_panel.clear()
            await pilot.pause()
            assert len(mounted_panel.children) == 0

    @pytest.mark.asyncio
    async def test_output_panel_append(self):
        """Test appending content to output panel."""
        panel = OutputPanel()
        async with run_widget_app(panel) as (mounted_panel, pilot):
            initial_count = len(mounted_panel.children)
            mounted_panel.append("Test message")
            await pilot.pause()
            assert len(mounted_panel.children) == initial_count + 1


class TestDebugPanel:
    """Test the DebugPanel component."""

    def test_debug_panel_initialization(self):
        """Test DebugPanel initializes correctly."""
        panel = DebugPanel()
        assert panel is not None

    @pytest.mark.asyncio
    async def test_debug_panel_clear(self):
        """Test clearing the debug panel."""
        panel = DebugPanel()
        async with run_widget_app(panel) as (mounted_panel, pilot):
            mounted_panel.append("Debug message 1")
            mounted_panel.append("Debug message 2")
            await pilot.pause()
            assert len(mounted_panel.children) == 2
            mounted_panel.clear()
            await pilot.pause()
            assert len(mounted_panel.children) == 0

    @pytest.mark.asyncio
    async def test_debug_panel_append(self):
        """Test appending messages to debug panel."""
        panel = DebugPanel()
        async with run_widget_app(panel) as (mounted_panel, pilot):
            initial_count = len(mounted_panel.children)
            mounted_panel.append("Debug message")
            await pilot.pause()
            assert len(mounted_panel.children) == initial_count + 1


class TestSettingsScreen:
    """Test the SettingsScreen modal."""

    def test_settings_screen_compose(self):
        """Test SettingsScreen composes correctly."""
        current_settings = {
            "concurrency": 16,
            "per_host": 8,
            "respect_robots": True,
            "verify_ssl": True,
            "debug_panel_enabled": False,
            "cache_enabled": True,
            "custom_headers": {},
        }
        screen = SettingsScreen(current_settings)
        # Patch Textual widget classes so compose doesn't require an active App.
        with patch("wxpath.tui.Vertical"), patch("wxpath.tui.Horizontal"), patch(
            "wxpath.tui.Static"
        ), patch("wxpath.tui.TextArea"), patch("wxpath.tui.Input"), patch(
            "wxpath.tui.Switch"
        ), patch(
            "wxpath.tui.Container"
        ), patch(
            "wxpath.tui.Button"
        ):
            widgets = list(screen.compose())
        assert len(widgets) > 0

    def test_settings_screen_gather(self):
        """Test gathering settings from widgets."""
        current_settings = {
            "concurrency": 16,
            "per_host": 8,
            "respect_robots": True,
            "verify_ssl": True,
            "debug_panel_enabled": False,
            "cache_enabled": True,
            "custom_headers": {},
        }
        screen = SettingsScreen(current_settings)
        # Mock the query_one to return appropriate "widgets" without using real Textual widgets
        def mock_query_one(selector):
            if "concurrency" in selector:
                widget = MagicMock()
                widget.value = "32"
                return widget
            elif "per_host" in selector:
                widget = MagicMock()
                widget.value = "16"
                return widget
            elif "respect_robots" in selector:
                widget = MagicMock()
                widget.value = False
                return widget
            elif "custom_headers" in selector:
                widget = MagicMock()
                widget.text = '{"User-Agent": "test"}'
                return widget
            else:
                widget = MagicMock()
                widget.value = True
                return widget

        screen.query_one = mock_query_one

        gathered = screen._gather()
        assert "concurrency" in gathered
        assert "per_host" in gathered

    def test_settings_screen_validate(self):
        """Test validation of settings."""
        current_settings = {
            "concurrency": 16,
            "per_host": 8,
            "respect_robots": True,
            "verify_ssl": True,
            "debug_panel_enabled": False,
            "cache_enabled": True,
            "custom_headers": {},
        }
        screen = SettingsScreen(current_settings)
        
        # Valid settings
        valid_data = {
            "concurrency": 16,
            "per_host": 8,
            "respect_robots": True,
            "verify_ssl": True,
            "debug_panel_enabled": False,
            "cache_enabled": True,
            "custom_headers": {},
        }
        error = screen._validate(valid_data)
        assert error is None
        
        # Invalid settings
        invalid_data = {"concurrency": 300}  # Too high
        error = screen._validate(invalid_data)
        assert error is not None

    def test_settings_screen_coerce_custom_headers(self):
        """Test coercion of custom headers from string to dict."""
        current_settings = {"custom_headers": {}}
        screen = SettingsScreen(current_settings)
        
        data = {"custom_headers": '{"User-Agent": "test"}'}
        screen._coerce_custom_headers(data)
        assert isinstance(data["custom_headers"], dict)
        assert data["custom_headers"] == {"User-Agent": "test"}
        
        # Empty string should become empty dict
        data = {"custom_headers": ""}
        screen._coerce_custom_headers(data)
        assert data["custom_headers"] == {}

    def test_settings_screen_button_pressed_save(self):
        """Test save button handling."""
        current_settings = {
            "concurrency": 16,
            "per_host": 8,
            "respect_robots": True,
            "verify_ssl": True,
            "debug_panel_enabled": False,
            "cache_enabled": True,
            "custom_headers": {},
        }
        screen = SettingsScreen(current_settings)
        
        # Mock methods
        screen._gather = MagicMock(return_value=current_settings)
        screen._validate = MagicMock(return_value=None)
        screen._coerce_custom_headers = MagicMock()
        screen.dismiss = MagicMock()
        
        with patch("wxpath.tui.save_tui_settings"):
            event = MagicMock()
            event.button.id = "settings-save-btn"
            screen.on_button_pressed(event)
            screen.dismiss.assert_called_once()

    def test_settings_screen_button_pressed_cancel(self):
        """Test cancel button handling."""
        current_settings = {}
        screen = SettingsScreen(current_settings)
        screen.dismiss = MagicMock()
        
        event = MagicMock()
        event.button.id = "settings-cancel-btn"
        screen.on_button_pressed(event)
        screen.dismiss.assert_called_once_with(None)

    def test_settings_screen_key_ctrl_s(self):
        """Test Ctrl+S key handling."""
        current_settings = {
            "concurrency": 16,
            "per_host": 8,
            "respect_robots": True,
            "verify_ssl": True,
            "debug_panel_enabled": False,
            "cache_enabled": True,
            "custom_headers": {},
        }
        screen = SettingsScreen(current_settings)
        
        screen._gather = MagicMock(return_value=current_settings)
        screen._validate = MagicMock(return_value=None)
        screen._coerce_custom_headers = MagicMock()
        screen.dismiss = MagicMock()
        
        with patch("wxpath.tui.save_tui_settings"):
            event = MagicMock()
            event.key = "ctrl+s"
            screen.on_key(event)
            screen.dismiss.assert_called_once()

    def test_settings_screen_key_escape(self):
        """Test Escape key handling."""
        current_settings = {}
        screen = SettingsScreen(current_settings)
        screen.dismiss = MagicMock()
        
        event = MagicMock()
        event.key = "escape"
        screen.on_key(event)
        screen.dismiss.assert_called_once_with(None)


class TestExportScreen:
    """Test the ExportScreen modal."""

    def test_export_screen_compose(self):
        """Test ExportScreen composes correctly."""
        screen = ExportScreen()
        # Patch core widgets so compose doesn't touch Textual internals or require App.
        with patch("wxpath.tui.Vertical"), patch("wxpath.tui.Container"), patch(
            "wxpath.tui.Static"
        ), patch("wxpath.tui.Button"):
            widgets = list(screen.compose())
        assert len(widgets) > 0

    def test_export_screen_button_csv(self):
        """Test CSV export button."""
        screen = ExportScreen()
        screen.dismiss = MagicMock()
        
        event = MagicMock()
        event.button.id = "export-csv-btn"
        screen.on_button_pressed(event)
        screen.dismiss.assert_called_once_with("csv")

    def test_export_screen_button_json(self):
        """Test JSON export button."""
        screen = ExportScreen()
        screen.dismiss = MagicMock()
        
        event = MagicMock()
        event.button.id = "export-json-btn"
        screen.on_button_pressed(event)
        screen.dismiss.assert_called_once_with("json")

    def test_export_screen_button_cancel(self):
        """Test cancel button."""
        screen = ExportScreen()
        screen.dismiss = MagicMock()
        
        event = MagicMock()
        event.button.id = "export-cancel-btn"
        screen.on_button_pressed(event)
        screen.dismiss.assert_called_once_with(None)

    def test_export_screen_key_escape(self):
        """Test Escape key handling."""
        screen = ExportScreen()
        screen.dismiss = MagicMock()
        
        event = MagicMock()
        event.key = "escape"
        screen.on_key(event)
        screen.dismiss.assert_called_once_with(None)
