"""Tests for TUI settings module.

Documentation generated by LLM - requires human review
pre-1.0.0 - APIs and contracts may change
"""

import json
import tempfile
from pathlib import Path
from unittest.mock import patch

from wxpath.tui_settings import (
    TUISettingsSchema,
    get_tui_settings_path,
    load_tui_settings,
    save_tui_settings,
    validate_tui_settings,
)


class TestTUISettingsSchema:
    """Test the TUI settings schema definition."""

    def test_schema_has_required_keys(self):
        """Test that all schema entries have required keys."""
        required_keys = {"key", "label", "type", "default"}
        for entry in TUISettingsSchema:
            assert all(key in entry for key in required_keys), f"Missing keys in {entry}"

    def test_schema_keys_are_unique(self):
        """Test that all schema keys are unique."""
        keys = [entry["key"] for entry in TUISettingsSchema]
        assert len(keys) == len(set(keys)), "Duplicate keys found in schema"

    def test_schema_types_are_valid(self):
        """Test that schema types are valid."""
        valid_types = {"int", "bool", "headers", "str"}
        for entry in TUISettingsSchema:
            assert entry["type"] in valid_types, f"Invalid type: {entry['type']}"

    def test_int_settings_have_min_max(self):
        """Test that integer settings have min/max constraints."""
        for entry in TUISettingsSchema:
            if entry["type"] == "int":
                assert "min" in entry, f"Missing min for {entry['key']}"
                assert "max" in entry, f"Missing max for {entry['key']}"


class TestValidateTUISettings:
    """Test TUI settings validation."""

    def test_validate_valid_settings(self):
        """Test validation with valid settings."""
        settings = {
            "concurrency": 16,
            "per_host": 8,
            "respect_robots": True,
            "verify_ssl": True,
            "debug_panel_enabled": False,
            "cache_enabled": True,
            "custom_headers": {},
        }
        errors = validate_tui_settings(settings)
        assert len(errors) == 0, f"Expected no errors, got: {errors}"

    def test_validate_invalid_concurrency_too_low(self):
        """Test validation rejects concurrency below minimum."""
        settings = {"concurrency": 0}
        errors = validate_tui_settings(settings)
        assert len(errors) > 0
        assert any("concurrency" in err.lower() and ">=" in err for err in errors)

    def test_validate_invalid_concurrency_too_high(self):
        """Test validation rejects concurrency above maximum."""
        settings = {"concurrency": 300}
        errors = validate_tui_settings(settings)
        assert len(errors) > 0
        assert any("concurrency" in err.lower() and "<=" in err for err in errors)

    def test_validate_invalid_per_host_too_low(self):
        """Test validation rejects per_host below minimum."""
        settings = {"per_host": 0}
        errors = validate_tui_settings(settings)
        assert len(errors) > 0

    def test_validate_invalid_per_host_too_high(self):
        """Test validation rejects per_host above maximum."""
        settings = {"per_host": 100}
        errors = validate_tui_settings(settings)
        assert len(errors) > 0

    def test_validate_invalid_type_concurrency(self):
        """Test validation rejects non-integer concurrency."""
        settings = {"concurrency": "not_an_int"}
        errors = validate_tui_settings(settings)
        assert len(errors) > 0
        assert any("concurrency" in err.lower() for err in errors)

    def test_validate_invalid_type_bool(self):
        """Test validation handles invalid bool types."""
        settings = {"respect_robots": "maybe"}
        # Should coerce or validate
        errors = validate_tui_settings(settings)
        # Validation may pass (coercion) or fail depending on implementation
        assert isinstance(errors, list)

    def test_validate_custom_headers_dict(self):
        """Test validation accepts valid headers dict."""
        settings = {"custom_headers": {"User-Agent": "test", "Accept": "text/html"}}
        errors = validate_tui_settings(settings)
        assert len(errors) == 0

    def test_validate_custom_headers_invalid_json_string(self):
        """Test validation rejects invalid JSON string."""
        settings = {"custom_headers": "{invalid json"}
        errors = validate_tui_settings(settings)
        assert len(errors) > 0
        assert any("custom_headers" in err.lower() for err in errors)

    def test_validate_custom_headers_non_dict_json(self):
        """Test validation rejects non-dict JSON."""
        settings = {"custom_headers": "[1, 2, 3]"}
        errors = validate_tui_settings(settings)
        assert len(errors) > 0

    def test_validate_custom_headers_non_string_values(self):
        """Test validation rejects headers with non-string values."""
        settings = {"custom_headers": {"User-Agent": 123}}
        errors = validate_tui_settings(settings)
        assert len(errors) > 0

    def test_validate_unknown_setting(self):
        """Test validation rejects unknown settings."""
        settings = {"unknown_setting": "value"}
        errors = validate_tui_settings(settings)
        assert len(errors) > 0
        assert any("unknown" in err.lower() for err in errors)


class TestLoadTUISettings:
    """Test loading TUI settings from file."""

    def test_load_settings_file_not_exists(self):
        """Test loading when config file doesn't exist returns defaults."""
        with patch("wxpath.tui_settings.get_tui_settings_path") as mock_path:
            mock_path.return_value = Path("/nonexistent/path/settings.json")
            settings = load_tui_settings()
            # Should return defaults
            assert isinstance(settings, dict)
            assert "concurrency" in settings
            assert "per_host" in settings

    def test_load_settings_valid_file(self):
        """Test loading from valid JSON file."""
        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            test_settings = {
                "concurrency": 32,
                "per_host": 16,
                "respect_robots": False,
                "cache_enabled": False,
                "custom_headers": {"User-Agent": "test"},
            }
            json.dump(test_settings, f)
            temp_path = Path(f.name)

        try:
            with patch("wxpath.tui_settings.get_tui_settings_path") as mock_path:
                mock_path.return_value = temp_path
                settings = load_tui_settings()
                assert settings["concurrency"] == 32
                assert settings["per_host"] == 16
                assert settings["respect_robots"] is False
                assert settings["cache_enabled"] is False
                assert settings["custom_headers"] == {"User-Agent": "test"}
        finally:
            temp_path.unlink()

    def test_load_settings_invalid_json(self):
        """Test loading from invalid JSON file returns defaults."""
        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            f.write("{invalid json}")
            temp_path = Path(f.name)

        try:
            with patch("wxpath.tui_settings.get_tui_settings_path") as mock_path:
                mock_path.return_value = temp_path
                settings = load_tui_settings()
                # Should return defaults
                assert isinstance(settings, dict)
                assert "concurrency" in settings
        finally:
            temp_path.unlink()

    def test_load_settings_partial_settings(self):
        """Test loading partial settings merges with defaults."""
        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            partial_settings = {"concurrency": 64}
            json.dump(partial_settings, f)
            temp_path = Path(f.name)

        try:
            with patch("wxpath.tui_settings.get_tui_settings_path") as mock_path:
                mock_path.return_value = temp_path
                settings = load_tui_settings()
                assert settings["concurrency"] == 64
                # Other settings should have defaults
                assert "per_host" in settings
                assert "respect_robots" in settings
        finally:
            temp_path.unlink()

    def test_load_settings_invalid_value_uses_default(self):
        """Test that invalid values in file use defaults."""
        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            invalid_settings = {"concurrency": "not_an_int"}
            json.dump(invalid_settings, f)
            temp_path = Path(f.name)

        try:
            with patch("wxpath.tui_settings.get_tui_settings_path") as mock_path:
                mock_path.return_value = temp_path
                settings = load_tui_settings()
                # Should use default for concurrency
                assert isinstance(settings["concurrency"], int)
        finally:
            temp_path.unlink()


class TestSaveTUISettings:
    """Test saving TUI settings to file."""

    def test_save_settings_creates_file(self):
        """Test saving creates the config file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            config_path = Path(tmpdir) / "tui_settings.json"
            with patch("wxpath.tui_settings.get_tui_settings_path") as mock_path:
                mock_path.return_value = config_path
                settings = {
                    "concurrency": 20,
                    "per_host": 10,
                    "respect_robots": True,
                    "verify_ssl": True,
                    "debug_panel_enabled": False,
                    "cache_enabled": True,
                    "custom_headers": {},
                }
                save_tui_settings(settings)
                assert config_path.exists()

    def test_save_settings_writes_valid_json(self):
        """Test saved file contains valid JSON."""
        with tempfile.TemporaryDirectory() as tmpdir:
            config_path = Path(tmpdir) / "tui_settings.json"
            with patch("wxpath.tui_settings.get_tui_settings_path") as mock_path:
                mock_path.return_value = config_path
                settings = {
                    "concurrency": 20,
                    "per_host": 10,
                    "respect_robots": True,
                    "cache_enabled": True,
                    "custom_headers": {"User-Agent": "test"},
                }
                save_tui_settings(settings)
                loaded = json.loads(config_path.read_text())
                assert loaded["concurrency"] == 20
                assert loaded["custom_headers"] == {"User-Agent": "test"}

    def test_save_settings_filters_unknown_keys(self):
        """Test saving filters out unknown keys."""
        with tempfile.TemporaryDirectory() as tmpdir:
            config_path = Path(tmpdir) / "tui_settings.json"
            with patch("wxpath.tui_settings.get_tui_settings_path") as mock_path:
                mock_path.return_value = config_path
                settings = {
                    "concurrency": 20,
                    "unknown_key": "should_not_be_saved",
                }
                save_tui_settings(settings)
                loaded = json.loads(config_path.read_text())
                assert "unknown_key" not in loaded
                assert "concurrency" in loaded

    def test_save_settings_includes_all_schema_keys(self):
        """Test saving includes all schema keys with defaults if missing."""
        with tempfile.TemporaryDirectory() as tmpdir:
            config_path = Path(tmpdir) / "tui_settings.json"
            with patch("wxpath.tui_settings.get_tui_settings_path") as mock_path:
                mock_path.return_value = config_path
                settings = {"concurrency": 20}
                save_tui_settings(settings)
                loaded = json.loads(config_path.read_text())
                # All schema keys should be present
                schema_keys = {entry["key"] for entry in TUISettingsSchema}
                assert schema_keys.issubset(set(loaded.keys()))


class TestGetTUISettingsPath:
    """Test getting TUI settings file path."""

    def test_get_path_uses_xdg_config_home(self, tmp_path):
        """Test path uses XDG_CONFIG_HOME when set."""
        custom_config = tmp_path / "custom" / "config"
        custom_config.mkdir(parents=True)
        
        with patch.dict("os.environ", {"XDG_CONFIG_HOME": str(custom_config)}):
            path = get_tui_settings_path()
            assert str(custom_config) in str(path)
            assert "wxpath" in str(path)
            assert path.name == "tui_settings.json"

    def test_get_path_falls_back_to_home(self, tmp_path):
        """Test path falls back to ~/.config when XDG_CONFIG_HOME not set."""
        fake_home = tmp_path / "home" / "user"
        fake_home.mkdir(parents=True)
        
        with patch.dict("os.environ", {}, clear=True):
            with patch("pathlib.Path.home") as mock_home:
                mock_home.return_value = fake_home
                path = get_tui_settings_path()
                assert str(fake_home) in str(path)
                assert ".config" in str(path)
                assert "wxpath" in str(path)
