"""Tests for WXPathTUI main application.

Documentation generated by LLM - requires human review
pre-1.0.0 - APIs and contracts may change
"""

from contextlib import asynccontextmanager
from types import SimpleNamespace
from typing import Any
from unittest.mock import MagicMock, patch

import pytest

try:
    from textual.widgets import DataTable, TextArea

    from wxpath.tui import WXPathTUI
except ImportError:
    pytest.skip("textual not available", allow_module_level=True)


@pytest.fixture(autouse=True)
def _isolate_xdg_config_home(monkeypatch: pytest.MonkeyPatch, tmp_path) -> None:
    """Isolate config writes to a temp directory during tests."""
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path))


@asynccontextmanager
async def run_tui_app() -> Any:
    """Run the TUI in Textual's test harness and yield (app, pilot)."""
    app = WXPathTUI()
    async with app.run_test() as pilot:  # type: ignore[attr-defined]
        await pilot.pause()
        yield app, pilot


class TestWXPathTUIValidation:
    """Test expression validation in WXPathTUI."""

    def test_validate_expression_valid(self):
        """Test validation of valid expressions."""
        app = WXPathTUI()
        
        valid_expressions = [
            "url('https://example.com')",
            "url('https://example.com')//div/text()",
            "url('https://example.com', depth=5)//div",
            "//div[@class='test']",
            "map { 'key': 'value' }",
            "url('test')//url(//a/@href)",
        ]
        
        for expr in valid_expressions:
            assert app._validate_expression(expr), f"Expression should be valid: {expr}"

    def test_validate_expression_unclosed_paren(self):
        """Test validation rejects unclosed parentheses."""
        app = WXPathTUI()
        assert not app._validate_expression("url('test'")
        assert not app._validate_expression("url('test')//div(")

    def test_validate_expression_unclosed_brace(self):
        """Test validation rejects unclosed braces."""
        app = WXPathTUI()
        assert not app._validate_expression("map { 'key': 'value'")
        assert not app._validate_expression("map { 'key': 'value' } //div {")

    def test_validate_expression_unclosed_bracket(self):
        """Test validation rejects unclosed brackets."""
        app = WXPathTUI()
        assert not app._validate_expression("//div[@class='test'")
        assert not app._validate_expression("//div[@class='test']//span[")

    def test_validate_expression_unclosed_quotes(self):
        """Test validation rejects unclosed quotes."""
        app = WXPathTUI()
        assert not app._validate_expression("url('test)")
        assert not app._validate_expression('url("test)')
        assert not app._validate_expression("//div[@class='test]")

    def test_validate_expression_escaped_quotes(self):
        """Test validation handles escaped quotes correctly."""
        app = WXPathTUI()
        # Escaped quotes should be valid
        assert app._validate_expression("url('test\\'quote')")
        assert app._validate_expression('url("test\\"quote")')


class TestWXPathTUIActions:
    """Test TUI action methods."""

    @pytest.mark.asyncio
    async def test_action_copy_expression(self):
        """Test copying expression to clipboard."""
        async with run_tui_app() as (app, pilot):
            editor = app.query_one("#expression-editor", TextArea)
            editor.text = "url('https://example.com')"
            await pilot.pause()

            app.copy_to_clipboard = MagicMock()
            app.action_copy_expression()

            app.copy_to_clipboard.assert_called_once_with("url('https://example.com')")

    @pytest.mark.asyncio
    async def test_action_clear(self):
        """Test clearing output panel."""
        async with run_tui_app() as (app, _pilot):
            app._update_output = MagicMock()
            app.action_clear()
            app._update_output.assert_called_once_with("Waiting for expression...")

    @pytest.mark.asyncio
    async def test_action_clear_editor(self):
        """Test clearing expression editor."""
        async with run_tui_app() as (app, pilot):
            editor = app.query_one("#expression-editor", TextArea)
            editor.text = "some expression"
            await pilot.pause()

            app.action_clear_editor()
            await pilot.pause()
            assert editor.text == ""

    @pytest.mark.asyncio
    async def test_action_clear_debug(self):
        """Test clearing debug panel."""
        async with run_tui_app() as (app, pilot):
            debug_panel = app.query_one("#debug-panel")
            debug_panel.append("Debug message")
            await pilot.pause()
            assert len(debug_panel.children) > 0

            app.action_clear_debug()
            await pilot.pause()
            assert len(debug_panel.children) == 0

    @pytest.mark.asyncio
    async def test_action_toggle_debug(self):
        """Test toggling debug panel visibility."""
        async with run_tui_app() as (app, pilot):
            initial_state = app.debug_panel_visible
            app.action_toggle_debug()
            await pilot.pause()
            assert app.debug_panel_visible != initial_state

            app.action_toggle_debug()
            await pilot.pause()
            assert app.debug_panel_visible == initial_state

    @pytest.mark.asyncio
    async def test_action_toggle_cache(self):
        """Test toggling cache."""
        async with run_tui_app() as (app, pilot):
            initial_state = app.cache_enabled
            await app.action_toggle_cache()
            await pilot.pause()
            assert app.cache_enabled != initial_state

    @pytest.mark.asyncio
    async def test_action_toggle_progress(self):
        """Test toggling progress bar."""
        async with run_tui_app() as (app, pilot):
            initial_state = app.progress_bar_enabled
            app.action_toggle_progress()
            await pilot.pause()
            assert app.progress_bar_enabled != initial_state


class TestWXPathTUIHelpers:
    """Test helper methods in WXPathTUI."""

    def test_prep_row_dict(self):
        """Test preparing row from dict result."""
        app = WXPathTUI()
        
        result = {"name": "Test", "age": 30, "city": "NYC"}
        keys = ["name", "age", "city"]
        row = app._prep_row(result, keys)
        
        assert row == ["Test", "30", "NYC"]

    def test_prep_row_xpathmap(self):
        """Test preparing row from XPathMap-like result."""
        app = WXPathTUI()
        
        # Simulate XPathMap with items() method
        class MockXPathMap:
            def items(self):
                return [("name", "Test"), ("age", 30)].__iter__()
        
        result = MockXPathMap()
        keys = ["name", "age"]
        row = app._prep_row(result, keys)
        
        assert "Test" in row
        assert "30" in row

    def test_prep_row_iterable_value(self):
        """Test preparing row with iterable values."""
        app = WXPathTUI()
        
        result = {"items": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]}
        keys = ["items"]
        row = app._prep_row(result, keys)
        
        # Should limit to first 10 items
        assert len(eval(row[0])) <= 10  # row[0] is string representation

    def test_prep_row_none_value(self):
        """Test preparing row with None values."""
        app = WXPathTUI()
        
        result = {"name": "Test", "age": None, "city": "NYC"}
        keys = ["name", "age", "city"]
        row = app._prep_row(result, keys)
        
        assert row[0] == "Test"
        assert row[1] == ""  # None should become empty string
        assert row[2] == "NYC"

    def test_prep_row_truncates_long_values(self):
        """Test very long cell values are truncated for TUI stability."""
        app = WXPathTUI()
        app._max_table_cell_chars = 20

        result = {"wiki_text": "x" * 200}
        keys = ["wiki_text"]
        row = app._prep_row(result, keys)

        assert row[0].endswith("...")
        assert len(row[0]) == 23

    def test_numeric_sort_key(self):
        """Test numeric sort key function."""
        app = WXPathTUI()
        
        # Numbers should sort numerically
        assert app._numeric_sort_key("2") < app._numeric_sort_key("10")
        assert app._numeric_sort_key(2) < app._numeric_sort_key(10)
        
        # Non-numeric should sort as strings
        assert app._numeric_sort_key("abc") > app._numeric_sort_key("2")
        
        # None/empty should sort last
        assert app._numeric_sort_key("") > app._numeric_sort_key("1")

    def test_clamp_split_percent(self):
        """Test split percent clamping bounds for panel resizing."""
        app = WXPathTUI()
        assert app._clamp_split_percent(10) == 20
        assert app._clamp_split_percent(50) == 50
        assert app._clamp_split_percent(90) == 80

    def test_is_numeric_column(self):
        """Test detecting numeric columns."""
        app = WXPathTUI()
        
        # Create a mock table with numeric values
        table = MagicMock(spec=DataTable)
        table.get_column = MagicMock(return_value=["1", "2", "3", "4", "5"])
        
        assert app._is_numeric_column(table, "test_column") is True
        
        # Non-numeric column
        table.get_column = MagicMock(return_value=["a", "b", "c", "d", "e"])
        assert app._is_numeric_column(table, "test_column") is False
        
        # Mixed column (majority numeric)
        table.get_column = MagicMock(return_value=["1", "2", "3", "a", "b"])
        assert app._is_numeric_column(table, "test_column") is True

    def test_escape_rich_markup(self):
        """Test escaping Rich markup brackets."""
        app = WXPathTUI()
        
        text = "Hello [world]"
        escaped = app._escape_rich_markup(text)
        assert escaped == "Hello \\[world\\]"
        
        text = "[bold]text[/bold]"
        escaped = app._escape_rich_markup(text)
        assert "\\[" in escaped and "\\]" in escaped

    def test_format_html_element(self):
        """Test formatting HTML elements."""
        from lxml.html import fromstring
        
        app = WXPathTUI()
        
        html_str = "<div><p>Test</p></div>"
        elem = fromstring(html_str)
        
        formatted = app._format_html_element(elem)
        assert isinstance(formatted, str)
        assert "Test" in formatted

    def test_format_dict(self):
        """Test formatting dictionaries."""
        app = WXPathTUI()
        
        d = {"name": "Test", "age": 30}
        formatted = app._format_dict(d)
        
        assert isinstance(formatted, str)
        assert "name" in formatted
        assert "Test" in formatted

    def test_format_dict_long_string(self):
        """Test formatting dict with long string values."""
        app = WXPathTUI()
        
        long_string = "a" * 150
        d = {"description": long_string}
        formatted = app._format_dict(d)
        
        # Should truncate to 100 chars
        assert len(formatted) < len(long_string) + 50  # Some overhead for formatting


class TestWXPathTUIExport:
    """Test export functionality."""

    @pytest.mark.asyncio
    async def test_get_output_data_table_no_table(self):
        """Test getting data table when none exists."""
        async with run_tui_app() as (app, _pilot):
            table = app._get_output_data_table()
            assert table is None

    @pytest.mark.asyncio
    async def test_get_output_data_table_with_table(self):
        """Test getting data table when one exists."""
        async with run_tui_app() as (app, pilot):
            output_panel = app.query_one("#output-panel")
            data_table = DataTable()
            output_panel.mount(data_table)
            await pilot.pause()

            table = app._get_output_data_table()
            assert table is not None
            assert table == data_table

    def test_export_table_csv(self, tmp_path):
        """Test exporting table to CSV."""
        app = WXPathTUI()
        
        # Create a mock data table
        table = MagicMock(spec=DataTable)
        col1 = MagicMock()
        col1.label = "Name"
        col2 = MagicMock()
        col2.label = "Age"
        table.ordered_columns = [col1, col2]
        
        row_meta = MagicMock()
        row_meta.key = "row1"
        table.ordered_rows = [row_meta]
        table.get_row = MagicMock(return_value=["John", "30"])
        
        csv_path = tmp_path / "test.csv"
        app._export_table_csv(table, csv_path)
        
        assert csv_path.exists()
        content = csv_path.read_text()
        assert "Name" in content
        assert "Age" in content
        assert "John" in content
        assert "30" in content

    def test_export_table_json(self, tmp_path):
        """Test exporting table to JSON."""
        app = WXPathTUI()
        
        # Create a mock data table
        table = MagicMock(spec=DataTable)
        col1 = MagicMock()
        col1.label = "Name"
        col2 = MagicMock()
        col2.label = "Age"
        table.ordered_columns = [col1, col2]
        
        row_meta = MagicMock()
        row_meta.key = "row1"
        table.ordered_rows = [row_meta]
        table.get_row = MagicMock(return_value=["John", "30"])
        
        json_path = tmp_path / "test.json"
        app._export_table_json(table, json_path)
        
        assert json_path.exists()
        import json
        content = json.loads(json_path.read_text())
        assert isinstance(content, list)
        assert len(content) == 1
        assert content[0]["Name"] == "John"
        assert content[0]["Age"] == "30"

    @pytest.mark.asyncio
    async def test_action_export_no_table(self):
        """Test export action when no table exists."""
        async with run_tui_app() as (app, _pilot):
            app._get_output_data_table = MagicMock(return_value=None)
            app.notify = MagicMock()
            app._debug = MagicMock()

            captured: dict[str, Any] = {}

            def fake_push_screen(_screen, callback):
                captured["callback"] = callback

            app.push_screen = fake_push_screen  # type: ignore[assignment]
            app.action_export()

            assert "callback" in captured
            captured["callback"]("csv")
            app.notify.assert_called_once()


class TestWXPathTUISettings:
    """Test settings-related functionality."""

    @pytest.mark.asyncio
    async def test_action_edit_settings(self):
        """Test opening settings screen."""
        async with run_tui_app() as (app, _pilot):
            app.push_screen = MagicMock()
            app._debug = MagicMock()
            app.action_edit_settings()
            app.push_screen.assert_called_once()

    @pytest.mark.asyncio
    async def test_watch_cache_enabled(self):
        """Test watching cache_enabled reactive."""
        async with run_tui_app() as (app, _pilot):
            with patch("wxpath.tui.save_tui_settings") as mock_save, patch(
                "wxpath.tui.SETTINGS"
            ) as mock_settings:
                mock_settings.http.client.cache.enabled = False
                app._debug = MagicMock()
                app._update_subtitle = MagicMock()
                app.tui_settings = {}

                app.watch_cache_enabled(True)

                assert mock_settings.http.client.cache.enabled is True
                app._update_subtitle.assert_called()
                mock_save.assert_called()

    @pytest.mark.asyncio
    async def test_watch_debug_panel_visible(self):
        """Test watching debug_panel_visible reactive."""
        async with run_tui_app() as (app, pilot):
            with patch("wxpath.tui.save_tui_settings") as mock_save:
                container = app.query_one("#debug-container")
                initial_display = container.display

                app.tui_settings = {}
                app.debug_panel_visible = not initial_display
                await pilot.pause()

                assert container.display == (not initial_display)
                mock_save.assert_called()


class TestWXPathTUIInitialization:
    """Test TUI initialization."""

    def test_tui_initialization(self):
        """Test TUI initializes correctly."""
        app = WXPathTUI()
        assert app._executing is False
        assert app._crawl_worker is None
        assert app._skip_next_live_execution is True

    @pytest.mark.asyncio
    async def test_tui_compose(self):
        """Test TUI composes all required widgets."""
        async with run_tui_app() as (app, _pilot):
            editor = app.query_one("#expression-editor", TextArea)
            assert editor is not None
            wsql_editor = app.query_one("#wsql-editor", TextArea)
            assert wsql_editor is not None

    @patch("wxpath.tui.load_tui_settings")
    @patch("wxpath.tui.save_tui_settings")
    @pytest.mark.asyncio
    async def test_tui_on_mount_loads_settings(self, _mock_save, mock_load):
        """Test that on_mount loads TUI settings."""
        mock_load.return_value = {
            "concurrency": 16,
            "per_host": 8,
            "respect_robots": True,
            "verify_ssl": True,
            "debug_panel_enabled": False,
            "cache_enabled": True,
            "custom_headers": {},
        }

        async with run_tui_app() as (_app, _pilot):
            mock_load.assert_called_once()


class TestWSQLIntegration:
    """Test optional WSQL integration behavior."""

    def test_create_wsql_executor_requires_enabled_flag(self):
        """Test WSQL executor creation requires explicit enablement."""
        app = WXPathTUI()
        app.wsql_enabled = False

        with pytest.raises(RuntimeError):
            app._create_wsql_executor()

    def test_create_wsql_executor_validates_install_path(self):
        """Test WSQL executor creation validates configured install path."""
        app = WXPathTUI()
        app.wsql_enabled = True
        app.wsql_install_path = "/definitely/not/a/real/path"

        with pytest.raises(ValueError):
            app._create_wsql_executor()

    def test_create_wsql_executor_success(self):
        """Test WSQL executor is built from runtime API."""
        app = WXPathTUI()
        app.wsql_enabled = True
        app.wsql_install_path = ""
        app._debug = MagicMock()

        class FakeExecutor:
            def __init__(self, **kwargs):
                self.kwargs = kwargs

        fake_module = SimpleNamespace(
            WSQLExecutor=FakeExecutor,
        )

        with patch(
            "wxpath.tui.importlib.import_module",
            return_value=fake_module,
        ) as mock_import:
            result = app._create_wsql_executor()

        assert isinstance(result, FakeExecutor)
        mock_import.assert_called_once_with("wsql.runtime.executor")
        assert result.kwargs["yield_errors"] is True
        assert result.kwargs["engine"] is None
