"""Tests for TextualProgressAdapter.

Documentation generated by LLM - requires human review
pre-1.0.0 - APIs and contracts may change
"""

from unittest.mock import MagicMock

import pytest

try:
    from wxpath.tui import TextualProgressAdapter
except ImportError:
    pytest.skip("textual not available", allow_module_level=True)


class TestTextualProgressAdapter:
    """Test the TextualProgressAdapter class."""

    def test_adapter_initialization(self):
        """Test adapter initializes with correct values."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock()
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=0)
        assert adapter.total == 0
        assert adapter._progress == 0

    def test_adapter_total_property(self):
        """Test total property getter and setter."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock()
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=10)
        assert adapter.total == 10
        
        adapter.total = 20
        assert adapter.total == 20
        mock_widget.update.assert_called()

    def test_adapter_update(self):
        """Test update method increments progress."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock()
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=10)
        adapter.update(5)
        assert adapter._progress == 5
        mock_widget.update.assert_called()

    def test_adapter_update_default(self):
        """Test update with default argument increments by 1."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock()
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=10)
        adapter.update()
        assert adapter._progress == 1

    def test_adapter_refresh(self):
        """Test refresh method updates widget."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock()
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=10)
        adapter.refresh()
        mock_widget.update.assert_called()

    def test_adapter_set_postfix(self):
        """Test set_postfix is a no-op (Textual ProgressBar has no postfix)."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock()
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=10)
        # Should not raise an error
        adapter.set_postfix(yielded=5, depth=2)

    def test_adapter_close(self):
        """Test close sets progress to total."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock()
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=10)
        adapter.close()
        assert adapter._progress == 10
        mock_widget.update.assert_called()

    def test_adapter_close_zero_total(self):
        """Test close with zero total sets progress to 1."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock()
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=0)
        adapter.close()
        assert adapter._progress == 1  # Should be 1 to avoid indeterminate

    def test_adapter_refresh_widget_exception_handling(self):
        """Test that exceptions in widget update are handled gracefully."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock(side_effect=Exception("Widget error"))
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=10)
        # Should not raise exception
        adapter.refresh()
        adapter.update(5)

    def test_adapter_widget_update_called_with_correct_params(self):
        """Test that widget.update is called with correct parameters."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock()
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=10)
        adapter.update(3)
        
        # Check that update was called with progress and total
        calls = mock_widget.update.call_args_list
        assert len(calls) > 0
        # Last call should have progress=3, total=10
        last_call = calls[-1]
        assert last_call.kwargs.get("progress") == 3
        assert last_call.kwargs.get("total") == 10

    def test_adapter_widget_update_with_zero_total(self):
        """Test widget update with zero total passes None."""
        mock_widget = MagicMock()
        mock_widget.update = MagicMock()
        get_widget = MagicMock(return_value=mock_widget)
        
        adapter = TextualProgressAdapter(get_widget, initial_total=0)
        adapter.update(1)
        
        calls = mock_widget.update.call_args_list
        assert len(calls) > 0
        last_call = calls[-1]
        # When total is 0, should pass None to indicate indeterminate
        assert last_call.kwargs.get("total") is None
