"""Additional tests for XPathContextRequired exception in patches.

Documentation generated by LLM - requires human review
pre-1.0.0 - APIs and contracts may change
"""

import pytest
from lxml import html

from wxpath.patches import XPathContextRequired, html_parser_with_xpath3


class TestXPathContextRequired:
    """Test XPathContextRequired exception."""

    def test_exception_message(self):
        """Test that exception has informative message."""
        error = XPathContextRequired()
        assert "XPathContext" in str(error)
        assert "required" in str(error).lower()

    def test_wx_depth_without_context(self):
        """Test wx:depth() raises XPathContextRequired without context."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        
        # Calling wx:depth() without a preceding "/" should raise XPathContextRequired
        with pytest.raises(XPathContextRequired):
            root.xpath3("wx:depth()")

    def test_wx_backlink_without_context(self):
        """Test wx:backlink() raises XPathContextRequired without context."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        
        with pytest.raises(XPathContextRequired):
            root.xpath3("wx:backlink()")

    def test_wx_current_url_without_context(self):
        """Test wx:current-url() raises XPathContextRequired without context."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        
        with pytest.raises(XPathContextRequired):
            root.xpath3("wx:current-url()")

    def test_wx_fetch_time_without_context(self):
        """Test wx:fetch-time() raises XPathContextRequired without context."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        
        with pytest.raises(XPathContextRequired):
            root.xpath3("wx:fetch-time()")

    def test_wx_status_code_without_context(self):
        """Test wx:status-code() raises XPathContextRequired without context."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        
        with pytest.raises(XPathContextRequired):
            root.xpath3("wx:status-code()")

    def test_wx_elem_without_context(self):
        """Test wx:elem() raises XPathContextRequired without context."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        
        with pytest.raises(XPathContextRequired):
            root.xpath3("wx:elem()")

    def test_wx_internal_links_without_context(self):
        """Test wx:internal-links() raises XPathContextRequired without context."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        
        with pytest.raises(XPathContextRequired):
            root.xpath3("wx:internal-links()")

    def test_wx_external_links_without_context(self):
        """Test wx:external-links() raises XPathContextRequired without context."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        
        with pytest.raises(XPathContextRequired):
            root.xpath3("wx:external-links()")

    def test_wx_main_article_text_without_context(self):
        """Test wx:main-article-text() raises XPathContextRequired without context."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        
        with pytest.raises(XPathContextRequired):
            root.xpath3("wx:main-article-text()")

    def test_wx_functions_with_context_work(self):
        """Test that wx: functions work correctly with proper context."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        root.set("depth", "3")
        root.base_url = "http://example.com"
        
        # With "/" prefix, should work
        result = root.xpath3("/wx:depth()")
        assert result == 3
        
        result = root.xpath3("/wx:current-url()")
        assert "example.com" in str(result[0])

    def test_exception_inheritance(self):
        """Test that XPathContextRequired is an Exception."""
        error = XPathContextRequired()
        assert isinstance(error, Exception)

    def test_exception_can_be_caught(self):
        """Test that XPathContextRequired can be caught."""
        html_str = "<html><body><p>Test</p></body></html>"
        root = html.fromstring(html_str, parser=html_parser_with_xpath3)
        
        caught = False
        try:
            root.xpath3("wx:depth()")
        except XPathContextRequired:
            caught = True
        
        assert caught
