"""Tests for _safe_iterator exception handling.

Documentation generated by LLM - requires human review
pre-1.0.0 - APIs and contracts may change
"""


from wxpath.core.exceptions import (
    XPathEvaluationError,
    XPathRuntimeError,
    XPathSyntaxError,
    XPathTypeError,
)
from wxpath.core.runtime.engine import _safe_iterator


class TestSafeIterator:
    """Test the _safe_iterator function."""

    def test_normal_iteration(self):
        """Test that _safe_iterator yields normal values correctly."""
        items = [1, 2, 3, 4, 5]
        result = list(_safe_iterator(items))
        assert result == [1, 2, 3, 4, 5]

    def test_empty_iterable(self):
        """Test that _safe_iterator handles empty iterables."""
        items = []
        result = list(_safe_iterator(items))
        assert result == []

    def test_single_item(self):
        """Test that _safe_iterator handles single item."""
        items = [42]
        result = list(_safe_iterator(items))
        assert result == [42]

    def test_xpath_evaluation_error(self):
        """Test that XPathEvaluationError is caught and converted to error dict."""
        def error_generator():
            yield 1
            raise XPathEvaluationError("XPath error", xpath="//div")
            yield 2  # This should not be reached
        
        result = list(_safe_iterator(error_generator()))
        assert len(result) == 2
        assert result[0] == 1
        assert isinstance(result[1], dict)
        assert result[1]["__type__"] == "error"
        assert result[1]["reason"] == "xpath_evaluation_error"
        assert "exception" in result[1]

    def test_xpath_syntax_error(self):
        """Test that XPathSyntaxError is caught and converted to error dict."""
        def error_generator():
            yield "first"
            raise XPathSyntaxError("Syntax error", xpath="//div[invalid")
            yield "second"
        
        result = list(_safe_iterator(error_generator()))
        assert len(result) == 2
        assert result[0] == "first"
        assert isinstance(result[1], dict)
        assert result[1]["__type__"] == "error"
        assert result[1]["reason"] == "xpath_evaluation_error"

    def test_xpath_type_error(self):
        """Test that XPathTypeError is caught and converted to error dict."""
        def error_generator():
            yield "item"
            raise XPathTypeError("Type error", xpath="//div + 'string'")
            yield "next"
        
        result = list(_safe_iterator(error_generator()))
        assert len(result) == 2
        assert result[0] == "item"
        assert isinstance(result[1], dict)
        assert result[1]["reason"] == "xpath_evaluation_error"

    def test_xpath_runtime_error(self):
        """Test that XPathRuntimeError is caught and converted to error dict."""
        def error_generator():
            yield "before"
            raise XPathRuntimeError("Runtime error", xpath="1 div 0")
            yield "after"
        
        result = list(_safe_iterator(error_generator()))
        assert len(result) == 2
        assert result[0] == "before"
        assert isinstance(result[1], dict)
        assert result[1]["reason"] == "xpath_evaluation_error"

    def test_generic_exception(self):
        """Test that generic exceptions are caught and converted to error dict."""
        def error_generator():
            yield "ok"
            raise ValueError("Generic error")
            yield "not reached"
        
        result = list(_safe_iterator(error_generator()))
        assert len(result) == 2
        assert result[0] == "ok"
        assert isinstance(result[1], dict)
        assert result[1]["__type__"] == "error"
        assert result[1]["reason"] == "iterator_error"
        assert "exception" in result[1]

    def test_multiple_errors(self):
        """Test that multiple errors are handled correctly."""
        # Note: When an exception is raised in a generator, it stops the generator
        # So we can only test one error per generator
        def error_generator():
            yield 1
            raise XPathEvaluationError("Error 1", xpath="//div1")
            # Generator stops here, so subsequent code never executes
        
        result = list(_safe_iterator(error_generator()))
        assert len(result) == 2  # 1, error1
        assert result[0] == 1
        assert result[1]["reason"] == "xpath_evaluation_error"

    def test_error_at_start(self):
        """Test that error at the start of iteration is handled."""
        def error_generator():
            raise XPathEvaluationError("First error", xpath="//div")
            yield "never"
        
        result = list(_safe_iterator(error_generator()))
        assert len(result) == 1
        assert result[0]["reason"] == "xpath_evaluation_error"

    def test_error_at_end(self):
        """Test that error at the end of iteration is handled."""
        def error_generator():
            yield "first"
            yield "second"
            raise XPathEvaluationError("Last error", xpath="//div")
        
        result = list(_safe_iterator(error_generator()))
        assert len(result) == 3
        assert result[0] == "first"
        assert result[1] == "second"
        assert result[2]["reason"] == "xpath_evaluation_error"

    def test_stop_iteration_handled(self):
        """Test that StopIteration is handled correctly (not converted to error)."""
        def normal_generator():
            yield 1
            yield 2
            # StopIteration is raised implicitly when generator ends
        
        result = list(_safe_iterator(normal_generator()))
        assert result == [1, 2]

    def test_error_dict_structure(self):
        """Test that error dictionaries have correct structure."""
        def error_generator():
            # Yield first to ensure generator is started
            yield "start"
            # Now raise error during iteration
            raise XPathEvaluationError("Test error", xpath="//test")
        
        result = list(_safe_iterator(error_generator()))
        assert len(result) == 2  # "start" and error dict
        error_dict = result[1]
        assert "__type__" in error_dict
        assert error_dict["__type__"] == "error"
        assert "reason" in error_dict
        assert "exception" in error_dict
        assert error_dict["reason"] == "xpath_evaluation_error"

    def test_error_message_included(self):
        """Test that error message is included in exception field."""
        error_msg = "Custom XPath error message"
        def error_generator():
            # Yield first to ensure generator is started
            yield "start"
            # Now raise error during iteration
            raise XPathEvaluationError(error_msg, xpath="//div")
        
        result = list(_safe_iterator(error_generator()))
        assert len(result) == 2  # "start" and error dict
        error_dict = result[1]
        # The exception string representation includes the error message
        exception_str = str(error_dict["exception"])
        assert error_msg in exception_str or error_msg in repr(error_dict["exception"])

    def test_iterator_preserves_order(self):
        """Test that iterator preserves order of items and errors."""
        # Note: When an exception is raised, the generator stops
        # So we can only test one error per generator
        def mixed_generator():
            yield "a"
            raise XPathEvaluationError("Error 1", xpath="//div1")
            # Generator stops here
        
        result = list(_safe_iterator(mixed_generator()))
        assert len(result) == 2
        assert result[0] == "a"
        assert result[1]["reason"] == "xpath_evaluation_error"
